spring:
  config:
    activate:
      on-profile: real
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
  session:
    store-type: jdbc