name: aws with spring ci/cd

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: set up jdk 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Caching
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: | 
            ${{ runner.os }}-gradle-

      - name: build
        run: ./gradlew clean build
        shell: bash

      - name: before deploy
        run: |
          zip -r aws_with_spring *
          mkdir -p deploy
          mv aws_with_spring.zip deploy/aws_with_spring.zip
        shell: bash

      - name: deploy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: upload to s3
        run: |
          pwd
          ls
          aws s3 cp --region ap-northeast-2 --acl private deploy s3://heekng-service-build/